### ISSUE TITLE
怎么设置打1联纸张?   我设置老出3联的纸张,后面全部是空白!

### ISSUE THREAD

**Issue by honganxue** [zhoujiulong/UsbConnectSample#1]

**Comment by zhoujiulong** [comment]
我知道的有两种情况会导致你这个问题
一种是代码设置的打印区域大小超出了你打印纸的大小
Printer.printAreaSize(0, 200, 200, 120, 1) 这个是设置打印区域的方法，具体的参考你那边的使用文档
一种是你要将你的设备进行打印校准一下，有时使用过程中打印机会错乱
这个要咨询下供应商你那个设备怎么进行校准的
